[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-src", "miri"]
targets = [
    "x86_64-unknown-linux-gnu",
    "thumbv7em-none-eabi",
    "thumbv7em-none-eabihf",
    "riscv32imc-unknown-none-elf",
]