[package]
name = "themql-embedded"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "themql-embedded"
path = "src/main.rs"

[target.'cfg(target_os = "none")'.dependencies]
embassy-executor = { workspace = true, features = ["platform-cortex-m", "executor-thread"] }
embassy-sync.workspace = true
embassy-time.workspace = true
cortex-m-rt.workspace = true
embedded-alloc.workspace = true
static_cell.workspace = true
minimq.workspace = true
embedded-io-async.workspace = true
themql-gnc = { path = "../themql-gnc", default-features = false }
themql-estimation = { path = "../themql-estimation", default-features = false }
nalgebra = { version = "0.35", default-features = false, features = ["libm"] }

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true
embedded-io-async.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
minimq.workspace = true

[package.metadata.cargo-machete]
ignored = ["cortex-m-rt"]

[target.'cfg(not(target_os = "none"))'.dependencies]
themql-gnc.workspace = true
themql-estimation.workspace = true
nalgebra.workspace = true