[package]
name = "themql-sse"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "themql_sse"
path = "src/lib.rs"

[dependencies]
tokio.workspace = true
themql-core.workspace = true
themql-message.workspace = true
thiserror.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true