[package]
name = "themql-sse"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "themql_sse"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true, features = ["rt", "sync", "io-util"] }
themql-core.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }