[package]
name = "themql-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "themql_runtime"
path = "src/lib.rs"

[features]
desktop = ["tokio"]
embedded = ["embassy-sync", "embassy-executor"]

[dependencies]
thiserror.workspace = true
tokio = { workspace = true, optional = true, features = ["rt", "time", "sync"] }
embassy-sync = { workspace = true, optional = true }
embassy-executor = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "time", "sync", "test-util", "macros"] }